#!/usr/bin/env bash
# Drive both pilot_ss binaries (Rust + C++) through pilot-bench and
# emit a side-by-side Markdown table. Run from anywhere; paths are
# anchored to the repo root.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
BENCH="${PILOT_BENCH_CLI:-$HOME/pilot-bench/build/cli/bench}"
RUST_BIN="$ROOT/target/release/pilot_ss"
CPP_BIN="$ROOT/cpp/build/pilot_ss_cpp"
PILOT_PRESET="${PILOT_PRESET:-quick}"
export PILOT_SS_ITERS_PERCENT="${PILOT_SS_ITERS_PERCENT:-100}"

if [[ ! -x "$BENCH" ]]; then
    echo "error: pilot-bench binary not found at $BENCH" >&2
    exit 1
fi
if [[ ! -x "$RUST_BIN" ]]; then
    echo "error: $RUST_BIN missing — run \`cargo build --release --bin pilot_ss\`" >&2
    exit 1
fi
if [[ ! -x "$CPP_BIN" ]]; then
    echo "error: $CPP_BIN missing — run \`cmake --build cpp/build\`" >&2
    exit 1
fi

measure() {
    local label=$1
    local op=$2
    local impl=$3
    local bin=$4
    local out mean ci rounds
    out=$("$BENCH" run_program --preset "$PILOT_PRESET" \
          --pi "${impl}_${op},ms/op,0,1,1" \
          -- "$bin" "$op" 2>&1)
    mean=$(echo "$out" | awk '/Reading mean/{print $5}')
    ci=$(echo "$out" | awk '/Reading CI/{print $5}')
    rounds=$(echo "$out" | awk '/^Rounds:/{print $2}')
    printf "%s|%s|%s|%s|%s\n" "$label" "$impl" "$mean" "±$ci" "$rounds"
}

OPS=(shamir_split shamir_reconstruct shamir_split_4kb shamir_reconstruct_4kb)

echo ""
echo "## Rust vs C++ — pilot-bench (k=3, n=5, GF(2^127 − 1))"
echo ""
echo "| Operation | impl | ms/op | ±CI (95%) | Runs |"
echo "|-----------|------|------:|----------:|-----:|"
for op in "${OPS[@]}"; do
    measure "$op" "$op" rust "$RUST_BIN" | awk -F'|' '{printf "| `%s` | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5}'
    measure "$op" "$op" cpp "$CPP_BIN"  | awk -F'|' '{printf "| `%s` | %s | %s | %s | %s |\n", $1, $2, $3, $4, $5}'
done
echo ""
echo "Generated by \`cpp/scripts/bench_compare.sh\` (preset: $PILOT_PRESET, PILOT_SS_ITERS_PERCENT=$PILOT_SS_ITERS_PERCENT)."
