//! Generate deterministic BigInt differential vectors for the C++ port.
//!
//! The emitted C++ header is consumed by
//! `cpp/test/test_bigint_differential.cpp`. Every expected value is
//! computed by this crate's BigInt and number-theory implementations,
//! which are the pinned `rump` reference for this contest. Regenerate
//! the header with `cpp/scripts/regen_bigint_vectors.sh`; compare it
//! with the committed copy using `cpp/scripts/check_bigint_vectors.sh`.

use secret_sharing::{
    field::{
        curve25519_field, curve448_field, mersenne127, mersenne521, nist_p192_field,
        nist_p224_field, nist_p256_field, nist_p384_field, poly1305_field, secp256k1_field,
    },
    primes::{gcd, mod_inverse},
    BigUint,
};

use std::collections::BTreeSet;

/// Deterministic bit patterns used to exercise limb boundaries and the
/// multiplication/division thresholds.
#[derive(Clone, Copy)]
enum Pattern {
    HighBit,
    AllOnes,
    HighBitWithLowNoise,
    RandomWithHighBit,
}

struct SplitMix64 {
    state: u64,
}

impl SplitMix64 {
    fn new() -> Self {
        Self {
            state: 0x243f_6a88_85a3_08d3,
        }
    }

    fn next_u64(&mut self) -> u64 {
        self.state = self.state.wrapping_add(0x9e37_79b9_7f4a_7c15);
        let mut z = self.state;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^ (z >> 31)
    }

    fn bytes(&mut self, len: usize) -> Vec<u8> {
        (0..len)
            .map(|_| self.next_u64() as u8)
            .collect::<Vec<_>>()
    }
}

struct Vectors {
    values: BTreeSet<(String, String, String, String, String)>,
}

impl Vectors {
    fn new() -> Self {
        Self {
            values: BTreeSet::new(),
        }
    }

    fn push(&mut self, operation: &str, lhs: &BigUint, rhs: &BigUint, result: &BigUint) {
        self.values.insert((
            operation.to_owned(),
            to_hex(lhs),
            to_hex(rhs),
            to_hex(result),
            String::new(),
        ));
    }

    fn push_div(&mut self, lhs: &BigUint, rhs: &BigUint, q: &BigUint, r: &BigUint) {
        if rhs.is_zero() {
            return;
        }
        self.values.insert((
            "div_rem".to_owned(),
            to_hex(lhs),
            to_hex(rhs),
            to_hex(q),
            to_hex(r),
        ));
    }

    fn push_sub(&mut self, lhs: &BigUint, rhs: &BigUint) {
        let (big, little) = if lhs >= rhs {
            (lhs, rhs)
        } else {
            (rhs, lhs)
        };
        self.push("sub", big, little, &big.sub_ref(little));
    }

    fn push_div_mod(&mut self, lhs: &BigUint, rhs: &BigUint) {
        if rhs.is_zero() {
            return;
        }
        let (q, r) = lhs.div_rem(rhs);
        self.push_div(lhs, rhs, &q, &r);
        self.push("modulo", lhs, rhs, &r);
    }

    fn push_mod_mul(&mut self, lhs: &BigUint, rhs: &BigUint, modulus: &BigUint) {
        if modulus.is_zero() {
            return;
        }
        self.values.insert((
            "mod_mul".to_owned(),
            to_hex(lhs),
            to_hex(rhs),
            to_hex(&BigUint::mod_mul(lhs, rhs, modulus)),
            to_hex(modulus),
        ));
    }

    fn push_inverse(&mut self, lhs: &BigUint, modulus: &BigUint) {
        if modulus <= &BigUint::from_u64(1) || lhs.is_zero() {
            return;
        }
        let reduced = lhs.modulo(modulus);
        if reduced.is_zero() || gcd(&reduced, modulus) != BigUint::from_u64(1) {
            return;
        }
        if let Some(inv) = mod_inverse(&reduced, modulus) {
            self.push("inverse", &reduced, modulus, &inv);
        }
    }

    fn emit_header(self) {
        println!("// Generated by `cargo run --release --example dump_bigint_vectors`.");
        println!("// Regenerate with `cpp/scripts/regen_bigint_vectors.sh`.");
        println!("#pragma once");
        println!();
        println!("#include <cstddef>");
        println!();
        println!("struct bigint_diff_vector {{");
        println!("    char const* operation;");
        println!("    char const* lhs;");
        println!("    char const* rhs;");
        println!("    char const* first;");
        println!("    char const* second;  // div_rem remainder, mod_mul modulus, else empty");
        println!("}};");
        println!();
        println!("inline constexpr bigint_diff_vector BIGINT_DIFF_VECTORS[] = {{");
        for (operation, lhs, rhs, first, second) in &self.values {
            println!(
                "    {{ \"{operation}\", \"{lhs}\", \"{rhs}\", \"{first}\", \"{second}\" }},",
            );
        }
        println!("}};");
        println!();
        println!("inline constexpr std::size_t BIGINT_DIFF_VECTOR_COUNT =");
        println!("    sizeof(BIGINT_DIFF_VECTORS) / sizeof(BIGINT_DIFF_VECTORS[0]);");
    }
}

fn main() {
    let mut rng = SplitMix64::new();
    let mut vectors = Vectors::new();
    let zero = BigUint::zero();
    let one = BigUint::from_u64(1);
    let two = BigUint::from_u64(2);
    let three = BigUint::from_u64(3);

    for a in [&zero, &one, &two, &three] {
        for b in [&zero, &one, &two, &three] {
            vectors.push("add", a, b, &a.add_ref(b));
            vectors.push_sub(a, b);
            vectors.push("mul", a, b, &a.mul_ref(b));
            vectors.push_div_mod(a, b);
            if *a != zero && *b != zero {
                vectors.push_mod_mul(a, b, b);
            }
            vectors.push_inverse(a, b);
        }
    }

    let widths = [1usize, 63, 64, 65, 127, 128, 129, 256, 384, 521, 522, 1024, 1025];
    let patterns = [
        Pattern::HighBit,
        Pattern::AllOnes,
        Pattern::HighBitWithLowNoise,
        Pattern::RandomWithHighBit,
    ];

    for width in widths {
        let values: Vec<_> = patterns
            .iter()
            .map(|&kind| from_pattern(width, kind, &mut rng))
            .collect();
        let one_for_width = &values[0];

        for (i, lhs) in values.iter().enumerate() {
            let rhs = &values[(i + 1) % values.len()];
            vectors.push("add", lhs, rhs, &lhs.add_ref(rhs));
            vectors.push_sub(lhs, rhs);
            vectors.push("mul", lhs, rhs, &lhs.mul_ref(rhs));
            vectors.push_div_mod(lhs, rhs);
        }

        let pair = (
            values[0].add_ref(&values[1]),
            values[1].mul_ref(&values[2]),
        );
        vectors.push_div_mod(&pair.0, &pair.1);
        vectors.push("add", &pair.0, &pair.1, &pair.0.add_ref(&pair.1));
        vectors.push_sub(&pair.0, &pair.1);

        for (i, modulus) in values.iter().enumerate() {
            let candidate_operands = [
                modulus.clone(),
                modulus.sub_ref(&one),
                one_for_width.clone(),
                values[(i + 2) % values.len()].clone(),
            ];
            let rhs = values[(i + 3) % values.len()].clone();
            for lhs in candidate_operands {
                vectors.push_mod_mul(&lhs, &rhs, modulus);
            }
        }
    }

    let prime_values = [
        mersenne127(),
        mersenne521(),
        curve25519_field(),
        poly1305_field(),
        secp256k1_field(),
        curve448_field(),
        nist_p192_field(),
        nist_p224_field(),
        nist_p256_field(),
        nist_p384_field(),
    ];
    for p in &prime_values {
        for lhs in [
            BigUint::from_u64(1),
            BigUint::from_u64(3),
            p.sub_ref(&one),
            p.sub_ref(&two),
            from_pattern(
                p.to_be_bytes().len() * 8,
                Pattern::RandomWithHighBit,
                &mut rng,
            ),
        ] {
            vectors.push_inverse(&lhs, p);
        }
    }

    for width in [64usize, 128, 256, 521] {
        for kind in [Pattern::AllOnes, Pattern::RandomWithHighBit] {
            let modulus = from_pattern(width, kind, &mut rng);
            let mut attempts = 0;
            while attempts < 8 {
                attempts += 1;
                let lhs = from_pattern(width, Pattern::RandomWithHighBit, &mut rng);
                vectors.push_inverse(&lhs, &modulus);
            }
        }
    }

    vectors.emit_header();
}

fn from_pattern(bits: usize, kind: Pattern, rng: &mut SplitMix64) -> BigUint {
    assert_ne!(bits, 0, "pattern width must be positive");
    let mut bytes = vec![0u8; bits.div_ceil(8)];
    let high_bit_in_byte = (bits - 1) % 8;
    let high_mask = 1u8 << high_bit_in_byte;
    let full_mask = 0xffu8 >> (7 - high_bit_in_byte);

    match kind {
        Pattern::HighBit => {
            bytes[0] |= high_mask;
        }
        Pattern::AllOnes => {
            bytes[0] = full_mask;
            for b in &mut bytes[1..] {
                *b = 0xff;
            }
        }
        Pattern::HighBitWithLowNoise => {
            bytes[0] = high_mask;
            let noise = rng.bytes(bytes.len() - 1);
            bytes[1..].copy_from_slice(&noise);
        }
        Pattern::RandomWithHighBit => {
            let noise = rng.bytes(bytes.len());
            bytes.copy_from_slice(&noise);
            bytes[0] = (bytes[0] & full_mask) | high_mask;
        }
    }

    let result = BigUint::from_be_bytes(&bytes);
    assert!(
        !result.to_be_bytes().is_empty() && result.to_be_bytes()[0] & high_mask != 0,
        "pattern must have the requested high bit"
    );
    result
}

fn to_hex(value: &BigUint) -> String {
    let bytes = value.to_be_bytes();
    if bytes.is_empty() {
        return "00".to_owned();
    }

    let mut out = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        out.push_str(&format!("{byte:02x}"));
    }
    out
}
