#!/usr/bin/env bash
# Drive every operation in `target/release/pilot_ss` through pilot-bench
# and emit a Markdown table with mean, ±CI (95%), and runs-to-CI.
#
# Pattern lifted from ../cryptography/scripts/bench_all_pk.sh; see that
# repo's pilot_pk.rs for the original reference.
#
# Env knobs:
#   PILOT_BENCH_CLI      path to pilot-bench `bench` binary (default
#                        $HOME/pilot-bench/build/cli/bench)
#   PILOT_SS_BIN         path to pilot_ss binary (default
#                        $ROOT/target/release/pilot_ss)
#   PILOT_PRESET         pilot-bench preset (default `quick` —
#                        20% CI of mean, 30 samples; switch to
#                        `normal` for 10% / 50 samples or `strict`
#                        for tight publication numbers)
#   PILOT_SS_ITERS_PERCENT  per-op iteration scale 1..=100 (default 25
#                           inside pilot_ss); raising this stretches
#                           each pilot-bench round.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BENCH="${PILOT_BENCH_CLI:-$HOME/pilot-bench/build/cli/bench}"
PILOT_SS="${PILOT_SS_BIN:-$ROOT_DIR/target/release/pilot_ss}"
PILOT_PRESET="${PILOT_PRESET:-quick}"
export PILOT_SS_ITERS_PERCENT="${PILOT_SS_ITERS_PERCENT:-25}"

if [[ ! -x "$BENCH" ]]; then
    echo "error: pilot-bench binary not found at $BENCH" >&2
    echo "set PILOT_BENCH_CLI or build pilot-bench first." >&2
    exit 1
fi
if [[ ! -x "$PILOT_SS" ]]; then
    echo "error: pilot_ss binary not built; run \`cargo build --release --bin pilot_ss\`" >&2
    exit 1
fi

measure() {
    local name=$1
    local out mean ci rounds
    out=$("$BENCH" run_program --preset "$PILOT_PRESET" \
          --pi "${name},ms/op,0,1,1" \
          -- "$PILOT_SS" "$name" 2>&1)
    mean=$(echo  "$out" | awk '/Reading mean/{print $5}')
    ci=$(echo    "$out" | awk '/Reading CI/{print $5}')
    rounds=$(echo "$out" | awk '/^Rounds:/{print $2}')
    printf "| %-40s | %10s | %10s | %5s |\n" \
           "$name" "$mean" "±$ci" "$rounds"
}

sep() { echo "|------------------------------------------|------------|------------|-------|"; }

hdr() {
    echo ""
    echo "### $1"
    echo ""
    echo "| Operation                                |   ms/op    | ±CI (95%)  | Runs  |"
    sep
}

hdr "Threshold (k=3, n=5, GF(2^127 − 1))"
measure shamir_split
measure shamir_reconstruct
measure blakley_split
measure blakley_reconstruct
measure kothari_split
measure kothari_reconstruct
measure karchmer_wigderson_split
measure karchmer_wigderson_reconstruct
measure brickell_split
measure brickell_reconstruct
measure massey_split
measure massey_reconstruct

hdr "Ramp / vector (k=3, L=k or L=k−1, n=5)"
measure ramp_split
measure ramp_reconstruct
measure yamamoto_split
measure yamamoto_reconstruct
measure blakley_meadows_split
measure blakley_meadows_reconstruct
measure kgh_split
measure kgh_reconstruct

hdr "Verifiable secret sharing"
measure vss_split
measure vss_reconstruct
measure cgma_vss_split
measure cgma_vss_reconstruct

hdr "CRT (small example sequences)"
measure mignotte_split
measure mignotte_reconstruct
measure mignotte_reconstruct_large
measure asmuth_bloom_split
measure asmuth_bloom_reconstruct

hdr "Other / convenience schemes"
measure trivial_split
measure trivial_reconstruct
measure ito_split
measure ito_reconstruct
measure benaloh_leichter_split
measure benaloh_leichter_reconstruct
measure proactive_refresh
measure proactive_recover
measure bytes_split_16
measure bytes_reconstruct_16
measure ida_split_16
measure ida_reconstruct_16
measure decode_reconstruct_t1

hdr "Visual cryptography (n=3, 8×8 image)"
measure visual_split_3_8
measure visual_decode_3_8

hdr "4 KiB block (k=3, n=5, GF(2^127 − 1), 274 × 15-byte chunks)"
measure shamir_split_4kb
measure shamir_reconstruct_4kb
measure blakley_split_4kb
measure blakley_reconstruct_4kb
measure kothari_split_4kb
measure kothari_reconstruct_4kb
measure karchmer_wigderson_split_4kb
measure karchmer_wigderson_reconstruct_4kb
measure brickell_split_4kb
measure brickell_reconstruct_4kb
measure massey_split_4kb
measure massey_reconstruct_4kb

echo ""
echo "Generated by \`scripts/bench_pilot.sh\` (preset: $PILOT_PRESET)."
