// Cross-language bit-compatibility tests.
//
// The Rust crate at the repository root ships an example,
// `examples/dump_compat_vectors.rs`, that emits deterministic test
// vectors covering the operations both implementations must agree
// on byte-for-byte. The vectors below are a copy of that output;
// the script `cpp/scripts/regen_compat.sh` regenerates them.
//
// What's covered:
// - ChaCha20 keystream from a fixed 32-byte seed (first 256 bytes).
// - BigUint multiplication: a * b for several operand pairs, with
//   the product encoded as big-endian bytes — so a transcription
//   error in the C++ port's limb layout is caught even if the
//   numerical result happens to match.
// - Shamir share reconstruction: given the share `(x, y)` byte
//   strings produced by the Rust impl on a fixed seed, the C++
//   reconstruct must recover the same secret.
//
// Anything in this file must remain bit-identical with what the
// Rust dump_compat_vectors example produces. Run the regen script
// after intentional changes.

#include "secret_sharing/bigint.hpp"
#include "secret_sharing/csprng.hpp"
#include "secret_sharing/field.hpp"
#include "secret_sharing/poly.hpp"
#include "secret_sharing/shamir.hpp"

#include <gtest/gtest.h>

#include <array>
#include <cstdint>
#include <span>
#include <vector>

namespace {

namespace ss = secret_sharing;

// Hex string → byte vector.
std::vector<std::uint8_t> hex_decode(std::string_view hex) {
    std::vector<std::uint8_t> out;
    out.reserve(hex.size() / 2);
    auto nib = [](char c) -> std::uint8_t {
        if (c >= '0' && c <= '9') {
            return static_cast<std::uint8_t>(c - '0');
        }
        if (c >= 'a' && c <= 'f') {
            return static_cast<std::uint8_t>(c - 'a' + 10);
        }
        if (c >= 'A' && c <= 'F') {
            return static_cast<std::uint8_t>(c - 'A' + 10);
        }
        throw std::runtime_error("bad hex char");
    };
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        out.push_back(static_cast<std::uint8_t>((nib(hex[i]) << 4) | nib(hex[i + 1])));
    }
    return out;
}

ss::big_uint big_from_hex(std::string_view hex) {
    auto bytes = hex_decode(hex);
    return ss::big_uint::from_be_bytes(std::span<std::uint8_t const>{bytes.data(), bytes.size()});
}

}  // namespace

// --------------------------------------------------------------------
// ChaCha20 keystream vectors. Same seed Rust uses in
// `csprng::tests::matches_rfc7539_test_vector_zero_key_zero_nonce`
// (already covered in `test_csprng.cpp`); this section exercises a
// non-trivial seed so the limb / endianness handling is also pinned.
// Vectors regenerated from `cargo run --example dump_compat_vectors`.

TEST(compat, chacha20_seed_a7_first_64_bytes) {
    std::array<std::uint8_t, 32> seed{};
    seed.fill(0xA7);
    auto rng = ss::chacha20_rng::from_seed(seed);
    std::array<std::uint8_t, 64> got{};
    rng.fill_bytes({got.data(), got.size()});

    // From Rust: ChaCha20Rng::from_seed(&[0xA7; 32]).fill_bytes(&mut [0; 64]).
    // Generated by `cargo run --release --example dump_compat_vectors`.
    constexpr std::array<std::uint8_t, 64> EXPECTED{
        0x85, 0x82, 0x0d, 0xe1, 0xec, 0x13, 0x02, 0x12, 0x19, 0x72, 0xcb, 0x25, 0xbb, 0xa1, 0xef,
        0xe0, 0xad, 0x1c, 0xf5, 0x97, 0x9b, 0xf9, 0x8e, 0xa3, 0xd0, 0xd4, 0x28, 0x66, 0x36, 0xd9,
        0x8a, 0xed, 0x98, 0x2f, 0x41, 0x88, 0x9a, 0x41, 0x8a, 0x29, 0xbb, 0x5f, 0xab, 0xbd, 0xfa,
        0xec, 0x27, 0xe5, 0x00, 0x55, 0xda, 0x6a, 0x63, 0x2b, 0x53, 0xee, 0xa6, 0xbd, 0x01, 0xa7,
        0xce, 0xf0, 0xb8, 0x42,
    };
    EXPECT_EQ(got, EXPECTED);
}

// --------------------------------------------------------------------
// BigUint multiplication: hex-encoded operand triples (a, b, a·b).
// a·b is mathematical, not modular. These are sanity checks on the
// limb layout / byte-encoding round trip.

struct mul_vector {
    char const* a_hex;
    char const* b_hex;
    char const* product_hex;
};

// Products generated by `cargo run --release --example dump_compat_vectors`.
constexpr mul_vector MUL_VECTORS[] = {
    {"01", "01", "01"},
    {"ff", "ff", "fe01"},
    {"deadbeef", "cafebabe", "b092ab7b88cf5b62"},
    {"0123456789abcdef", "fedcba9876543210", "0121fa00ad77d7422236d88fe5618cf0"},
};

TEST(compat, biguint_multiplication_vectors) {
    for (auto const& v : MUL_VECTORS) {
        auto a = big_from_hex(v.a_hex);
        auto b = big_from_hex(v.b_hex);
        auto prod = a.mul_ref(b);
        auto bytes = prod.to_be_bytes();
        auto expected_bytes = hex_decode(v.product_hex);
        EXPECT_EQ(bytes, expected_bytes)
            << "mul vector failed: a=" << v.a_hex << " b=" << v.b_hex;
    }
}

// --------------------------------------------------------------------
// Per-prime field multiplication. Same operands across all primes;
// each prime's mul reduces to its own residue. Pinning these byte
// strings catches any divergence between the Rust catalogue and the
// C++ catalogue — in particular, a sign error in a Solinas term or
// a constant-table typo in either constructor.

struct field_mul_vector {
    char const* name;
    char const* product_hex;
    ss::big_uint (*p_ctor)();
};

constexpr char const* OPERAND_A_HEX = "deadbeefcafebabe0123456789abcdef";
constexpr char const* OPERAND_B_HEX = "fedcba9876543210cafef00dba5eba11";

inline std::vector<field_mul_vector> field_mul_vectors() {
    return {
        {"mersenne127", "0cd1b5cb7a62014b0a5cd1ae2444a70c", &ss::mersenne127},
        {"mersenne521",
         "ddb06310dc4c1aa054508af7743d2a14d170efa9c1c9cc0a61bbbbbf3bca52df", &ss::mersenne521},
        {"curve25519",
         "5db06310dc4c1aa054508af7743d2a14d170efa9c1c9cc0a61bbbbbf3bca52f2",
         &ss::curve25519_field},
        {"poly1305", "01e68d6b7ed528ed52cb2069748d16c778", &ss::poly1305_field},
        {"secp256k1",
         "ddb06310dc4c1aa054508af7743d2a14d170efa9c1c9cc0a61bbbbbf3bca52df",
         &ss::secp256k1_field},
        {"curve448",
         "ddb06310dc4c1aa054508af7743d2a14d170efa9c1c9cc0a61bbbbbf3bca52df",
         &ss::curve448_field},
        {"nist_p192", "54508af7743d2a15af2152ba9e15e6ab3f6c1ed018166d7f", &ss::nist_p192_field},
        {"nist_p224",
         "dc4c1aa054508af7743d2a15af2152b9c1c9cc0a61bbbbbe5e19efcf", &ss::nist_p224_field},
        {"nist_p256",
         "ddb06310dc4c1aa054508af7743d2a14d170efa9c1c9cc0a61bbbbbf3bca52df",
         &ss::nist_p256_field},
        {"nist_p384",
         "ddb06310dc4c1aa054508af7743d2a14d170efa9c1c9cc0a61bbbbbf3bca52df",
         &ss::nist_p384_field},
    };
}

TEST(compat, per_prime_field_mul_matches_rust) {
    auto a_bytes = hex_decode(OPERAND_A_HEX);
    auto b_bytes = hex_decode(OPERAND_B_HEX);
    auto a = ss::big_uint::from_be_bytes({a_bytes.data(), a_bytes.size()});
    auto b = ss::big_uint::from_be_bytes({b_bytes.data(), b_bytes.size()});
    for (auto const& v : field_mul_vectors()) {
        auto p = v.p_ctor();
        auto f = ss::prime_field::new_unchecked(p);
        auto a_red = a.modulo(p);
        auto b_red = b.modulo(p);
        auto prod = f.mul(a_red, b_red);
        auto bytes = prod.to_be_bytes();
        EXPECT_EQ(bytes, hex_decode(v.product_hex)) << "prime: " << v.name;
        EXPECT_LT(prod, p) << v.name;
    }
}

// --------------------------------------------------------------------
// Shamir round trip across the FFI boundary.
//
// Vectors below come from running the Rust impl with seed [0xC1; 32],
// secret = 0xC0FFEEDEADBEEF, k = 3, n = 5 over Mersenne-127. Each
// share's (x, y) field elements are encoded as big-endian hex.
// Reconstruction with the C++ impl must recover the same secret.

struct share_vector {
    char const* x_hex;
    char const* y_hex;
};

// Filled in by `cpp/scripts/regen_compat.sh` from the Rust dumper.
// Until that lands, the test below dynamically generates vectors via
// the C++ impl with the same seed and verifies round-trip recovery —
// that pins the C++ side to itself, and the cross-language pin is
// upgraded once the dumper regenerates these arrays.
// Vectors from `cargo run --release --example dump_compat_vectors`
// with seed [0xC1; 32], secret = 0xC0FFEEDEADBEEF, k = 3, n = 5
// over Mersenne-127.
constexpr std::array<share_vector, 5> SHAMIR_SHARES{{
    {"01", "603372317dac55ab4abb349dd0e465e8"},
    {"02", "67e82f4f612cf3435aa9231edb9e575a"},
    {"03", "171e3759aa81d8c8308acb71fedb9345"},
    {"04", "6dd58a5059ab0639cc602d973a9c19a7"},
    {"05", "6c0e28336ea87b982e29498e8edfea82"},
}};

TEST(compat, shamir_round_trip_self_consistent) {
    // (a) Self-consistency: split + reconstruct in C++ recovers the
    // original secret.
    auto p = ss::mersenne127();
    auto f = ss::prime_field::new_unchecked(p);
    std::array<std::uint8_t, 32> seed{};
    seed.fill(0xC1);
    auto rng = ss::chacha20_rng::from_seed(seed);
    auto secret = ss::big_uint::from_u128(0xC0FFEEDEADBEEFULL);
    auto shares = ss::shamir::split(f, rng, secret, 3, 5);
    auto recovered = ss::shamir::reconstruct(
        f, std::span<ss::share const>{shares.data(), 3}, 3);
    ASSERT_TRUE(recovered.has_value());
    EXPECT_EQ(*recovered, secret);
}

TEST(compat, shamir_share_bytes_match_rust) {
    // (b) Bit-for-bit: each share's (x, y) byte string produced by
    // the C++ split with the same seed equals the Rust output.
    auto f = ss::prime_field::new_unchecked(ss::mersenne127());
    std::array<std::uint8_t, 32> seed{};
    seed.fill(0xC1);
    auto rng = ss::chacha20_rng::from_seed(seed);
    auto secret = ss::big_uint::from_u128(0xC0FFEEDEADBEEFULL);
    auto shares = ss::shamir::split(f, rng, secret, 3, 5);
    ASSERT_EQ(shares.size(), SHAMIR_SHARES.size());
    for (std::size_t i = 0; i < shares.size(); ++i) {
        auto x_bytes = shares[i].x.to_be_bytes();
        auto y_bytes = shares[i].y.to_be_bytes();
        EXPECT_EQ(x_bytes, hex_decode(SHAMIR_SHARES[i].x_hex)) << "share " << i << " x";
        EXPECT_EQ(y_bytes, hex_decode(SHAMIR_SHARES[i].y_hex)) << "share " << i << " y";
    }
}

TEST(compat, shamir_reconstruct_from_rust_shares) {
    // (c) Cross-language: parse Rust's shares directly, reconstruct
    // in C++, and check the recovered secret. This is the test that
    // would catch a wire-format divergence.
    auto f = ss::prime_field::new_unchecked(ss::mersenne127());
    std::vector<ss::share> shares;
    for (auto const& v : SHAMIR_SHARES) {
        ss::share s;
        s.x = big_from_hex(v.x_hex);
        s.y = big_from_hex(v.y_hex);
        shares.push_back(std::move(s));
    }
    auto recovered = ss::shamir::reconstruct(
        f, std::span<ss::share const>{shares.data(), 3}, 3);
    ASSERT_TRUE(recovered.has_value());
    EXPECT_EQ(*recovered, ss::big_uint::from_u128(0xC0FFEEDEADBEEFULL));
}
