#include "secret_sharing/bigint.hpp"

#include <gtest/gtest.h>

#include <cstdint>
#include <random>
#include <string>
#include <string_view>
#include <vector>

namespace {

namespace ss = secret_sharing;

ss::big_uint from_hex(std::string_view hex) {
    auto nibble = [](char c) -> std::uint8_t {
        if (c >= '0' && c <= '9') {
            return static_cast<std::uint8_t>(c - '0');
        }
        return static_cast<std::uint8_t>(c - 'a' + 10);
    };
    std::vector<std::uint8_t> bytes;
    bytes.reserve((hex.size() + 1) / 2);
    if (hex.size() % 2 != 0) {
        bytes.push_back(nibble(hex.front()));
        hex.remove_prefix(1);
    }
    for (std::size_t i = 0; i + 1 < hex.size(); i += 2) {
        bytes.push_back(static_cast<std::uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
    }
    return ss::big_uint::from_be_bytes({bytes.data(), bytes.size()});
}

ss::big_uint from_u64(std::uint64_t v) { return ss::big_uint(v); }

ss::big_uint seeded_biguint(std::size_t words, std::mt19937_64& rng) {
    std::vector<std::uint8_t> bytes(words * 8);
    for (auto& b : bytes) {
        b = static_cast<std::uint8_t>(rng());
    }
    if (!bytes.empty() && bytes[0] == 0) {
        bytes[0] = 1;  // ensure top byte non-zero so the limb count is `words`
    }
    return ss::big_uint::from_be_bytes({bytes.data(), bytes.size()});
}

struct splitmix64 {
    std::uint64_t state;

    std::uint64_t next() {
        state = static_cast<std::uint64_t>(state + 0x9e3779b97f4a7c15ull);
        auto z = state;
        z = static_cast<std::uint64_t>((z ^ (z >> 30U)) * 0xbf58476d1ce4e5b9ull);
        z = static_cast<std::uint64_t>((z ^ (z >> 27U)) * 0x94d049bb133111ebull);
        return static_cast<std::uint64_t>(z ^ (z >> 31U));
    }
};

std::uint64_t structured_limb(splitmix64& rng) {
    auto const raw = rng.next();
    switch (raw % 8U) {
        case 0:
            return 0;
        case 1:
            return UINT64_MAX;
        case 2:
            return 1;
        case 3:
            return static_cast<std::uint64_t>(1) << 63U;
        case 4:
            return (static_cast<std::uint64_t>(1) << 63U) | 1U;
        case 5:
            return UINT64_MAX - 1U;
        default:
            return rng.next();
    }
}

ss::big_uint from_limbs(std::vector<std::uint64_t> const& limbs) {
    std::vector<std::uint8_t> bytes(limbs.size() * 8);
    auto out = bytes.begin();
    for (auto it = limbs.rbegin(); it != limbs.rend(); ++it) {
        auto const limb = *it;
        for (int byte = 7; byte >= 0; --byte) {
            *out++ = static_cast<std::uint8_t>(limb >> (byte * 8));
        }
    }
    return ss::big_uint::from_be_bytes({bytes.data(), bytes.size()});
}

ss::big_uint structured_biguint(std::size_t words, splitmix64& rng) {
    std::vector<std::uint64_t> limbs(words);
    for (std::size_t i = 0; i < words; ++i) {
        limbs[i] = structured_limb(rng);
    }
    return from_limbs(limbs);
}

ss::big_uint power_of_two(std::size_t bit) {
    ss::big_uint out;
    out.set_bit(bit);
    return out;
}

std::pair<ss::big_uint, ss::big_uint> bitwise_div_rem(ss::big_uint const& dividend,
                                                      ss::big_uint const& divisor) {
    ss::big_uint quotient;
    ss::big_uint remainder;
    for (std::size_t bit_idx = dividend.bits(); bit_idx-- > 0;) {
        remainder.shl1();
        if (dividend.bit(bit_idx)) {
            remainder.set_bit(0);
        }
        if (!(remainder < divisor)) {
            remainder.sub_assign_ref(divisor);
            quotient.set_bit(bit_idx);
        }
    }
    return {std::move(quotient), std::move(remainder)};
}

void expect_division_identity(ss::big_uint const& dividend, ss::big_uint const& divisor) {
    ASSERT_FALSE(divisor.is_zero());
    auto [quotient, remainder] = dividend.div_rem(divisor);
    EXPECT_LT(remainder, divisor);
    EXPECT_EQ(quotient.mul_ref(divisor).add_ref(remainder), dividend);
    EXPECT_EQ(dividend.modulo(divisor), remainder);
}

void expect_division_matches_bitwise(ss::big_uint const& dividend, ss::big_uint const& divisor) {
    ASSERT_FALSE(divisor.is_zero());
    auto [quotient, remainder] = dividend.div_rem(divisor);
    auto [expected_q, expected_r] = bitwise_div_rem(dividend, divisor);
    SCOPED_TRACE("dividend_bits=" + std::to_string(dividend.bits())
                 + " divisor_bits=" + std::to_string(divisor.bits()));
    EXPECT_EQ(quotient, expected_q);
    EXPECT_EQ(remainder, expected_r);
    expect_division_identity(dividend, divisor);
}

TEST(big_uint, algorithm_d_edge_cases) {
    // Generated by gen_algod_vectors.py and checked against Python integers.
    // Branch labels describe the generator's model, not instrumented C++ coverage.
    struct Vec {
        const char* dividend;
        const char* divisor;
        const char* quotient;
        const char* remainder;
        const char* tag;
        const char* branches;
    };
    static const Vec kVec[] = {
    {"00", "80000000000000000000000000000000", "00", "00", "smalldiv", ""},
    {"01", "80000000000000000000000000000000", "00", "01", "smalldiv", ""},
    {"7fffffffffffffff", "80000000000000000000000000000000", "00", "7fffffffffffffff", "smalldiv", ""},
    {"8000000000000000", "80000000000000000000000000000000", "00", "8000000000000000", "smalldiv", ""},
    {"80000000000000000000000000000000", "80000000000000000000000000000000", "01", "00", "shift0", ""},
    {"80000000000000000000000000000001", "80000000000000000000000000000000", "01", "01", "shift0", ""},
    {"80000000000000007fffffffffffffff", "80000000000000000000000000000000", "01", "7fffffffffffffff", "shift0", ""},
    {"80000000000000008000000000000000", "80000000000000000000000000000000", "01", "8000000000000000", "shift0", ""},
    {"7fffffffffffffff80000000000000000000000000000000", "80000000000000000000000000000000", "ffffffffffffffff", "00", "shift0", ""},
    {"7fffffffffffffff80000000000000000000000000000001", "80000000000000000000000000000000", "ffffffffffffffff", "01", "shift0", ""},
    {"7fffffffffffffff80000000000000007fffffffffffffff", "80000000000000000000000000000000", "ffffffffffffffff", "7fffffffffffffff", "shift0", ""},
    {"7fffffffffffffff80000000000000008000000000000000", "80000000000000000000000000000000", "ffffffffffffffff", "8000000000000000", "shift0", ""},
    {"080000000000000000000000000000000000000000000000", "80000000000000000000000000000000", "1000000000000000", "00", "lowlimb0", ""},
    {"080000000000000000000000000000000000000000000001", "80000000000000000000000000000000", "1000000000000000", "01", "lowlimb0", ""},
    {"080000000000000000000000000000007fffffffffffffff", "80000000000000000000000000000000", "1000000000000000", "7fffffffffffffff", "lowlimb0", ""},
    {"ffffffffffffffff0000000000000000", "ffffffffffffffff0000000000000000", "01", "00", "lowlimb0", ""},
    {"ffffffffffffffff0000000000000001", "ffffffffffffffff0000000000000000", "01", "01", "lowlimb0", ""},
    {"fffffffffffffffffffffffffffffffe", "ffffffffffffffff0000000000000000", "01", "fffffffffffffffe", "lowlimb0", ""},
    {"0ffffffffffffffff0000000000000000000000000000000", "ffffffffffffffff0000000000000000", "1000000000000000", "00", "lowlimb0", ""},
    {"0ffffffffffffffff0000000000000000000000000000001", "ffffffffffffffff0000000000000000", "1000000000000000", "01", "lowlimb0", ""},
    {"0ffffffffffffffff000000000000000fffffffffffffffe", "ffffffffffffffff0000000000000000", "1000000000000000", "fffffffffffffffe", "lowlimb0", ""},
    {"fffffffffffffffe00000000000000010000000000000000", "ffffffffffffffff0000000000000000", "ffffffffffffffff", "00", "lowlimb0", ""},
    {"fffffffffffffffe00000000000000010000000000000001", "ffffffffffffffff0000000000000000", "ffffffffffffffff", "01", "lowlimb0", ""},
    {"fffffffffffffffe0000000000000001fffffffffffffffe", "ffffffffffffffff0000000000000000", "ffffffffffffffff", "fffffffffffffffe", "lowlimb0", ""},
    {"8000000000000000000000000000000000000000000000000000000000000000", "80000000000000000000000000000001", "fffffffffffffffffffffffffffffffe", "02", "clamp", "clamp"},
    {"8000000000000000000000000000000000000000000000010000000000000001", "80000000000000000000000000000001", "fffffffffffffffffffffffffffffffe", "010000000000000003", "clamp", "clamp"},
    {"80000000000000000000000000000000ffffffffffffffffffffffffffffffff", "80000000000000000000000000000001", "ffffffffffffffffffffffffffffffff", "80000000000000000000000000000000", "clamp", "clamp"},
    {"80000000000000000000000000000000000000000000000000000000000000000000000000000000", "80000000000000000000000000000001", "fffffffffffffffffffffffffffffffe0000000000000000", "020000000000000000", "clamp", "clamp"},
    {"80000000000000000000000000000000000000000000000100000000000000010000000000000001", "80000000000000000000000000000001", "fffffffffffffffffffffffffffffffe0000000000000002", "02ffffffffffffffff", "clamp", "clamp"},
    {"80000000000000000000000000000000ffffffffffffffffffffffffffffffffffffffffffffffff", "80000000000000000000000000000001", "ffffffffffffffffffffffffffffffffffffffffffffffff", "80000000000000000000000000000000", "clamp", "clamp"},
    {"8000000000000000000000000000000000000000000000000000000000000000", "80000000000000000000000000000002", "fffffffffffffffffffffffffffffffc", "08", "clamp", "clamp"},
    {"8000000000000000000000000000000000000000000000010000000000000001", "80000000000000000000000000000002", "fffffffffffffffffffffffffffffffc", "010000000000000009", "clamp", "clamp"},
    {"80000000000000000000000000000000ffffffffffffffffffffffffffffffff", "80000000000000000000000000000002", "fffffffffffffffffffffffffffffffe", "03", "clamp", "clamp"},
    {"8000000000000000000000000000000100000000000000000000000000000000", "80000000000000000000000000000002", "fffffffffffffffffffffffffffffffe", "04", "clamp", "clamp"},
    {"8000000000000000000000000000000100000000000000010000000000000001", "80000000000000000000000000000002", "fffffffffffffffffffffffffffffffe", "010000000000000005", "clamp", "clamp"},
    {"80000000000000000000000000000001ffffffffffffffffffffffffffffffff", "80000000000000000000000000000002", "ffffffffffffffffffffffffffffffff", "80000000000000000000000000000001", "clamp", "clamp"},
    {"80000000000000000000000000000000000000000000000000000000000000000000000000000000", "80000000000000000000000000000002", "fffffffffffffffffffffffffffffffc0000000000000000", "080000000000000000", "clamp", "clamp"},
    {"80000000000000000000000000000000000000000000000100000000000000010000000000000001", "80000000000000000000000000000002", "fffffffffffffffffffffffffffffffc0000000000000002", "08fffffffffffffffd", "clamp", "clamp"},
    {"800000000000000080000000000000000000000000000000", "800000000000000080000000000000000000000000000001", "00", "800000000000000080000000000000000000000000000000", "smalldiv", ""},
    {"01000000000000000100000000000000000000000000000000", "800000000000000080000000000000000000000000000001", "01", "80000000000000007fffffffffffffffffffffffffffffff", "addback", "addback"},
    {"ffffffffffffffffffffffffffffffff00000000000000010000000000000000", "800000000000000080000000000000000000000000000001", "01fffffffffffffffd", "80000000000000007fffffffffffffff0000000000000003", "addback", "addback"},
    {"800000000000000080000000000000000000000000000000", "800000000000000080000000000000000000000000000002", "00", "800000000000000080000000000000000000000000000000", "smalldiv", ""},
    {"01000000000000000100000000000000000000000000000000", "800000000000000080000000000000000000000000000002", "01", "80000000000000007ffffffffffffffffffffffffffffffe", "addback", "addback"},
    {"800000000000000080000000000000000000000000000000", "800000000000000080000000000000000000000000000003", "00", "800000000000000080000000000000000000000000000000", "smalldiv", ""},
    {"01000000000000000100000000000000000000000000000000", "800000000000000080000000000000000000000000000003", "01", "80000000000000007ffffffffffffffffffffffffffffffd", "addback", "addback"},
    {"800000000000000080000000000000000000000000000000", "800000000000000080000000000000007fffffffffffffff", "00", "800000000000000080000000000000000000000000000000", "smalldiv", ""},
    {"8000000000000000800000000000000000000000000000000000000000000000", "800000000000000080000000000000000000000000000001", "ffffffffffffffff", "80000000000000007fffffffffffffff0000000000000001", "addback+clamp+rbreak", "addback+clamp+rbreak"},
    {"8000000000000000800000000000000000000000000000000000000000000000", "800000000000000080000000000000000000000000000002", "ffffffffffffffff", "80000000000000007ffffffffffffffe0000000000000002", "addback+clamp+rbreak", "addback+clamp+rbreak"},
    {"8000000000000000800000000000000000000000000000010000000000000000", "800000000000000080000000000000000000000000000002", "ffffffffffffffff", "80000000000000007fffffffffffffff0000000000000002", "addback+clamp+rbreak", "addback+clamp+rbreak"},
    {"8000000000000000800000000000000000000000000000000000000000000000", "800000000000000080000000000000000000000000000003", "ffffffffffffffff", "80000000000000007ffffffffffffffd0000000000000003", "addback+clamp+rbreak", "addback+clamp+rbreak"},
    {"8000000000000000800000000000000000000000000000010000000000000000", "800000000000000080000000000000000000000000000003", "ffffffffffffffff", "80000000000000007ffffffffffffffe0000000000000003", "addback+clamp+rbreak", "addback+clamp+rbreak"},
    {"8000000000000000800000000000000000000000000000000000000000000000", "800000000000000080000000000000007fffffffffffffff", "ffffffffffffffff", "800000000000000000000000000000017fffffffffffffff", "addback+clamp+rbreak", "addback+clamp+rbreak"},
    {"123456789abcdeefffffffffffffffff7fffffffffffffffedcba98765432110", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8c", "349a32cf5ef75b41db9882797b19f5d0", "nearmultiple", ""},
    {"123456789abcdeefffffffffffffffff7fffffffffffffffedcba98765432111", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8c", "349a32cf5ef75b41db9882797b19f5d1", "nearmultiple", ""},
    {"123456789abcdeefffffffffffffffffffffffffffffffffffffffffffffffff", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8d", "349a32cf5ef75b41db9882797b19f5cf", "nearmultiple", ""},
    {"123456789abcdef0000000000000000000000000000000000000000000000000", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8d", "349a32cf5ef75b41db9882797b19f5d0", "nearmultiple", ""},
    {"123456789abcdef0000000000000000000000000000000000000000000000001", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8d", "349a32cf5ef75b41db9882797b19f5d1", "nearmultiple", ""},
    {"123456789abcdef000000000000000008000000000000000123456789abcdeef", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8e", "349a32cf5ef75b41db9882797b19f5cf", "nearmultiple", ""},
    {"123456789abcdef000000000000000008000000000000000123456789abcdef0", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8e", "349a32cf5ef75b41db9882797b19f5d0", "nearmultiple", ""},
    {"123456789abcdef000000000000000008000000000000000123456789abcdef1", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8e", "349a32cf5ef75b41db9882797b19f5d1", "nearmultiple", ""},
    {"123456789abcdef0000000000000000100000000000000002468acf13579bddf", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8f", "349a32cf5ef75b41db9882797b19f5cf", "nearmultiple", ""},
    {"123456789abcdeeffffffffffffffffeffffffffffffffffdb97530eca864220", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8b", "349a32cf5ef75b41db9882797b19f5d0", "nearmultiple", ""},
    {"123456789abcdeeffffffffffffffffeffffffffffffffffdb97530eca864221", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8b", "349a32cf5ef75b41db9882797b19f5d1", "nearmultiple", ""},
    {"123456789abcdeefffffffffffffffff7fffffffffffffffedcba9876543210f", "8000000000000000123456789abcdef0", "2468acf13579bddffad2648f30254c8c", "349a32cf5ef75b41db9882797b19f5cf", "nearmultiple", ""},
    };

    for (const auto& v : kVec) {
        SCOPED_TRACE(v.tag);
        auto u = from_hex(v.dividend);
        auto d = from_hex(v.divisor);
        auto expected_q = from_hex(v.quotient);
        auto expected_r = from_hex(v.remainder);
        auto [q, r] = u.div_rem(d);
        EXPECT_EQ(q, expected_q);
        EXPECT_EQ(r, expected_r);
        EXPECT_EQ(q.mul_ref(d).add_ref(r), u);
    }
}


}  // namespace

TEST(big_uint, default_is_zero) {
    ss::big_uint v;
    EXPECT_TRUE(v.is_zero());
    EXPECT_EQ(v.bits(), 0u);
}

TEST(big_uint, from_u128_round_trip) {
    auto v = ss::big_uint::from_u128((__uint128_t{0xDEADBEEFu} << 64) | 0xCAFEBABEull);
    auto bytes = v.to_be_bytes();
    auto round = ss::big_uint::from_be_bytes({bytes.data(), bytes.size()});
    EXPECT_EQ(v, round);
}

TEST(big_uint, add_sub_mul_small) {
    auto a = ss::big_uint::from_u128(1'000'000'000'000ull);
    auto b = ss::big_uint::from_u128(777'777'777'777ull);
    EXPECT_EQ(a.add_ref(b), ss::big_uint::from_u128(1'777'777'777'777ull));
    EXPECT_EQ(a.sub_ref(from_u64(1)), ss::big_uint::from_u128(999'999'999'999ull));
    EXPECT_EQ(a.mul_ref(b),
              ss::big_uint::from_u128(__uint128_t{777'777'777'777ull} * 1'000'000'000'000ull));
}

TEST(big_uint, division_round_trip) {
    auto dividend = ss::big_uint::from_u128(1'234'567'890'123'456'789ull);
    auto divisor = from_u64(37);
    auto [q, r] = dividend.div_rem(divisor);
    EXPECT_EQ(q.mul_ref(divisor).add_ref(r), dividend);
    EXPECT_LT(r, divisor);
}

TEST(big_uint, division_round_trip_across_divisor_widths) {
    // One-limb divisors take the short-division path; wider divisors
    // take the bit-by-bit loop. Both must satisfy q·d + r = n, r < d.
    std::mt19937_64 rng{0xb7e151628aed2a6aull};
    for (auto [dividend_words, divisor_words] :
         {std::pair{4u, 1u}, {6u, 2u}, {8u, 3u}, {5u, 5u}}) {
        for (int trial = 0; trial < 4; ++trial) {
            auto dividend = seeded_biguint(dividend_words, rng);
            auto divisor = seeded_biguint(divisor_words, rng);
            auto [q, r] = dividend.div_rem(divisor);
            EXPECT_LT(r, divisor);
            EXPECT_EQ(q.mul_ref(divisor).add_ref(r), dividend);
        }
    }
}

TEST(big_uint, division_matches_bitwise_reference_over_limb_shapes) {
    splitmix64 rng{0x5a5a5a5a5a5a5a5aull};
    for (std::size_t dividend_words = 1; dividend_words <= 8; ++dividend_words) {
        for (std::size_t divisor_words = 1; divisor_words <= dividend_words; ++divisor_words) {
            for (int trial = 0; trial < 24; ++trial) {
                auto dividend = structured_biguint(dividend_words, rng);
                auto divisor = structured_biguint(divisor_words, rng);
                if (!divisor.is_zero()) {
                    expect_division_matches_bitwise(dividend, divisor);
                }
            }
        }
    }
}

TEST(big_uint, division_boundary_relationships) {
    splitmix64 rng{0x1111111111111111ull};
    for (std::size_t divisor_words = 1; divisor_words <= 6; ++divisor_words) {
        for (int trial = 0; trial < 16; ++trial) {
            auto divisor = structured_biguint(divisor_words, rng);
            if (divisor.is_zero()) {
                continue;
            }
            for (std::size_t multiplier_words = 1; multiplier_words <= 3; ++multiplier_words) {
                auto multiplier = structured_biguint(multiplier_words, rng);
                if (multiplier.is_zero()) {
                    continue;
                }
                auto exact = multiplier.mul_ref(divisor);
                expect_division_matches_bitwise(exact, divisor);
                expect_division_matches_bitwise(exact.add_ref(ss::big_uint::one()), divisor);
                expect_division_matches_bitwise(exact.sub_ref(ss::big_uint::one()), divisor);
            }
        }
    }
}

TEST(big_uint, division_normalization_shift_extremes) {
    splitmix64 rng{0x2222222222222222ull};
    constexpr std::uint64_t TOPS[] = {
        1, 2, 3, UINT64_MAX, static_cast<std::uint64_t>(1) << 63U,
        (static_cast<std::uint64_t>(1) << 63U) | 1U, static_cast<std::uint64_t>(1) << 62U,
    };
    for (auto const top : TOPS) {
        for (std::size_t divisor_words = 1; divisor_words <= 5; ++divisor_words) {
            for (std::size_t dividend_words = divisor_words; dividend_words <= 7; ++dividend_words) {
                for (int trial = 0; trial < 8; ++trial) {
                    std::vector<std::uint64_t> divisor_limbs(divisor_words);
                    for (std::size_t i = 0; i < divisor_words; ++i) {
                        divisor_limbs[i] = structured_limb(rng);
                    }
                    divisor_limbs[divisor_words - 1] = top;
                    auto divisor = from_limbs(divisor_limbs);
                    auto dividend = structured_biguint(dividend_words, rng);
                    expect_division_matches_bitwise(dividend, divisor);
                }
            }
        }
    }
}

TEST(big_uint, division_worst_case_quotient_estimates) {
    constexpr std::uint64_t TOPS[] = {
        static_cast<std::uint64_t>(1) << 63U,
        (static_cast<std::uint64_t>(1) << 63U) | 1U,
        (static_cast<std::uint64_t>(1) << 63U) | (static_cast<std::uint64_t>(1) << 62U),
        UINT64_MAX - 1U,
        UINT64_MAX,
    };
    auto limb_pattern = [](std::size_t index, std::size_t len, int pattern) -> std::uint64_t {
        switch (pattern) {
            case 0:
                return 0;
            case 1:
                return UINT64_MAX;
            case 2:
                return index % 2 == 0 ? std::uint64_t{0} : UINT64_MAX;
            case 3:
                return index == 0 ? std::uint64_t{1} : std::uint64_t{0};
            case 4:
                return index + 2 == len ? std::uint64_t{1} : std::uint64_t{0};
            default:
                return index % 2 == 0 ? UINT64_MAX : std::uint64_t{1};
        }
    };

    for (std::size_t words = 2; words <= 6; ++words) {
        for (auto const top : TOPS) {
            for (int pattern = 0; pattern < 6; ++pattern) {
                std::vector<std::uint64_t> limbs(words);
                for (std::size_t i = 0; i < words; ++i) {
                    limbs[i] = limb_pattern(i, words, pattern);
                }
                limbs[words - 1] = top;
                auto divisor = from_limbs(limbs);
                if (divisor.is_zero()) {
                    continue;
                }
                for (std::size_t shift_limbs = 1; shift_limbs <= 3; ++shift_limbs) {
                    auto shifted = divisor;
                    shifted.shl_bits(64 * shift_limbs);
                    expect_division_matches_bitwise(shifted.sub_ref(ss::big_uint::one()), divisor);
                    expect_division_matches_bitwise(
                        shifted.sub_ref(ss::big_uint(std::uint64_t{2})), divisor);
                    expect_division_matches_bitwise(shifted, divisor);
                    expect_division_matches_bitwise(shifted.add_ref(ss::big_uint::one()), divisor);
                }
            }
        }
    }
}

TEST(big_uint, division_estimate_overshoot_by_two) {
    auto base = power_of_two(64);
    constexpr std::uint64_t TOPS[] = {
        static_cast<std::uint64_t>(1) << 63U,
        (static_cast<std::uint64_t>(1) << 63U) | 1U,
        (static_cast<std::uint64_t>(1) << 63U) | (static_cast<std::uint64_t>(1) << 62U),
        UINT64_MAX - 1U,
        UINT64_MAX,
    };
    constexpr std::uint64_t LOWS[] = {1, 2, 5, UINT64_MAX};
    constexpr std::uint64_t REST[] = {0, 1, UINT64_MAX};
    for (auto const d : TOPS) {
        for (auto const v0 : LOWS) {
            for (std::size_t words = 3; words <= 6; ++words) {
                std::vector<std::uint64_t> limbs(words, d);
                limbs[0] = v0;
                auto divisor = from_limbs(limbs);
                auto remainder = divisor.sub_ref(ss::big_uint::one());
                for (auto const u0 : REST) {
                    auto dividend = divisor.add_ref(remainder).mul_ref(base).add_ref(ss::big_uint(u0));
                    expect_division_matches_bitwise(dividend, divisor);
                }
            }
        }
    }
}

TEST(big_uint, division_powers_of_two) {
    constexpr std::size_t DIVIDEND_BITS[] = {0, 1, 63, 64, 65, 127, 128, 255, 256, 511, 512, 1023};
    constexpr std::size_t DIVISOR_BITS[] = {0, 1, 63, 64, 65, 127, 128, 255, 256};
    for (auto const dividend_bit : DIVIDEND_BITS) {
        for (auto const divisor_bit : DIVISOR_BITS) {
            auto dividend = power_of_two(dividend_bit);
            auto divisor = power_of_two(divisor_bit);
            expect_division_matches_bitwise(dividend, divisor);
            expect_division_matches_bitwise(dividend.add_ref(ss::big_uint::one()), divisor);
            if (divisor_bit > 0) {
                expect_division_matches_bitwise(dividend, divisor.sub_ref(ss::big_uint::one()));
            }
        }
    }
}

TEST(big_uint, division_degenerate_inputs) {
    auto one = ss::big_uint::one();
    std::vector<std::uint8_t> bytes(64, 0xFF);
    auto big = ss::big_uint::from_be_bytes({bytes.data(), bytes.size()});
    expect_division_matches_bitwise(ss::big_uint::zero(), one);
    expect_division_matches_bitwise(ss::big_uint::zero(), big);
    expect_division_matches_bitwise(one, one);
    expect_division_matches_bitwise(big, one);
    expect_division_matches_bitwise(big, big);
    expect_division_matches_bitwise(big, big.sub_ref(one));
    expect_division_matches_bitwise(big.sub_ref(one), big);

    auto [quotient, remainder] = one.div_rem(big);
    EXPECT_TRUE(quotient.is_zero());
    EXPECT_EQ(remainder, one);
}

TEST(big_uint, mod_mul_matches_bitwise_reference_and_montgomery) {
    splitmix64 rng{0x3333333333333333ull};
    for (std::size_t words : {1u, 2u, 4u, 8u}) {
        for (int trial = 0; trial < 16; ++trial) {
            auto lhs = structured_biguint(words, rng);
            auto rhs = structured_biguint(words, rng);
            auto modulus = structured_biguint(words, rng);
            if (modulus.is_zero() || modulus.is_one()) {
                continue;
            }
            auto product = ss::big_uint::mod_mul(lhs, rhs, modulus);
            auto expected = bitwise_div_rem(lhs.mul_ref(rhs), modulus).second;
            EXPECT_EQ(product, expected);
            EXPECT_LT(product, modulus);
            if (modulus.is_odd()) {
                auto ctx = ss::montgomery_ctx::make(modulus);
                ASSERT_TRUE(ctx.has_value());
                EXPECT_EQ(product, ctx->mul(lhs, rhs));
            }
        }
    }
}

TEST(big_uint, mul_dispatch_matches_schoolbook) {
    // Sizes straddle the Karatsuba threshold (128 limbs). Schoolbook is
    // private, so build the reference by decomposing one operand into
    // 64-limb chunks: each chunk·b partial product has a short side well
    // under the threshold and therefore dispatches to schoolbook, and
    // the shifted sum of the partials must equal the full product.
    constexpr std::size_t CHUNK_LIMBS = 64;
    std::mt19937_64 rng{0x9e3779b97f4a7c15ull};
    for (auto words : {64u, 128u, 160u, 256u}) {
        for (int trial = 0; trial < 4; ++trial) {
            auto a = seeded_biguint(words, rng);
            auto b = seeded_biguint(words, rng);
            auto via_dispatch = a.mul_ref(b);

            auto reference = ss::big_uint::zero();
            for (std::size_t start = 0; start < words; start += CHUNK_LIMBS) {
                auto chunk = a.shr_bits(start * 64).low_bits(CHUNK_LIMBS * 64);
                auto part = chunk.mul_ref(b);
                part.shl_bits(start * 64);
                reference.add_assign_ref(part);
            }
            EXPECT_EQ(via_dispatch, reference);
        }
    }
}

TEST(big_uint, to_be_bytes_is_compact) {
    EXPECT_EQ(ss::big_uint::zero().to_be_bytes(), std::vector<std::uint8_t>{0});
    auto v = ss::big_uint::from_u128(0x0102030405060708ull);
    EXPECT_EQ(v.to_be_bytes(),
              (std::vector<std::uint8_t>{0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08}));
}

// `from_be_bytes` reserves `(n+7)/8` limbs but `normalise()` may pop
// trailing zero limbs, leaving the live vector range (`size()`) smaller
// than the owned allocation (`capacity()`). Returns such a value.
static ss::big_uint underfull_from_bytes(std::vector<std::uint8_t> bytes) {
    return ss::big_uint::from_be_bytes({bytes.data(), bytes.size()});
}

TEST(big_uint, destroys_shrunk_storage_safely_under_sanitizers) {
    // The destructor scrubs the full owned allocation. When size() <
    // capacity() (here a high zero limb normalised away), wiping the
    // capacity directly through data() writes past the live range and
    // trips ASan's container-overflow; the fix extends the live range
    // to the capacity first. This test can only establish absence of
    // that illegal access under the sanitizer build — it does not
    // itself observe the wipe.
    {
        auto v = underfull_from_bytes({0x00, 0x00, 0x00, 0x00, 0x00,
                                       0x00, 0x00, 0x00, 0x01});
        EXPECT_EQ(v.to_be_bytes(), (std::vector<std::uint8_t>{0x01}));
    }  // One live limb with spare capacity; destructor runs here.

    // Normalising all the way to empty: live range is zero.
    {
        auto v = underfull_from_bytes({0x00, 0x00, 0x00, 0x00, 0x00,
                                       0x00, 0x00, 0x00, 0x00});
        EXPECT_TRUE(v.is_zero());
    }

    // The destination owns the retained allocation after the move.
    {
        auto a = underfull_from_bytes({0x00, 0x00, 0x00, 0x00, 0x00,
                                       0x00, 0x00, 0x00, 0x01});
        auto b = std::move(a);
        EXPECT_EQ(b.to_be_bytes(), (std::vector<std::uint8_t>{0x01}));
    }
}

TEST(big_uint, shr_low_round_trip) {
    std::mt19937_64 rng{0x243f6a8885a308d3ull};
    for (int trial = 0; trial < 200; ++trial) {
        std::size_t words = (rng() % 12) + 1;
        auto x = seeded_biguint(words, rng);
        for (auto k : {0u, 1u, 7u, 31u, 63u, 64u, 65u, 100u, 127u, 128u, 129u, 200u}) {
            if (k > x.bits() + 64) {
                continue;
            }
            auto high = x.shr_bits(k);
            auto low = x.low_bits(k);
            EXPECT_LE(low.bits(), k);
            auto hk = high;
            hk.shl_bits(k);
            EXPECT_EQ(hk.add_ref(low), x);
        }
    }
}

TEST(big_uint, shl_bits_zero_is_identity) {
    auto x = ss::big_uint::from_u128(0xDEADBEEFCAFEBABEull);
    auto y = x;
    y.shl_bits(0);
    EXPECT_EQ(x, y);
}

TEST(big_uint, mod_mul_matches_textbook) {
    auto a = from_u64(123'456'789);
    auto b = from_u64(987'654'321);
    auto m = from_u64(1'000'000'007);
    EXPECT_EQ(ss::big_uint::mod_mul(a, b, m), from_u64(259'106'859));
}

TEST(big_uint, mod_mul_even_modulus) {
    // Even moduli take the same one-shot multiply/reduce path now that
    // `mod_mul` does not special-case Montgomery setup.
    auto a = from_u64(37);
    auto b = from_u64(19);
    auto m = from_u64(100);
    EXPECT_EQ(ss::big_uint::mod_mul(a, b, m), from_u64(3));
}

TEST(big_uint, set_bit_grows_limbs) {
    ss::big_uint v;
    v.set_bit(127);
    EXPECT_EQ(v.bits(), 128u);
    EXPECT_TRUE(v.bit(127));
    EXPECT_FALSE(v.bit(126));
}

TEST(big_uint, ordering_distinguishes_limb_lengths) {
    auto small = from_u64(0xFFFFFFFFFFFFFFFFull);
    auto big = small.add_ref(ss::big_uint::one());
    EXPECT_LT(small, big);
    EXPECT_GT(big, small);
    EXPECT_NE(small, big);
}
